version: "3.9"
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx:
    environment:
      VIRTUAL_HOST: testing.local
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public
      - ./storage/app/public:/app/public/storage


  php:
    build:
      target: dev
    depends_on:
      - composer
      - db
    volumes:
      - ./:/app
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./storage/app/public:/app/public/storage



  composer:
    image: composer:2.7.7
    working_dir: /app
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts


volumes:
  postgres_data:


